package org.amire.progav_finalproj.utils;

public enum ActionTypes {
    ToLogin,
    ToRegister,
    Login,
    StartRegister,
    EndRegister,
    Logout,
    AjoutFavorisEcole,
    RetraitFavorisEcole,
    AjoutPosulationEcole,
    ModifPosulationEcole,
    RetraitPosulationEcole,
    EcoleVersDashboard,
    EcoleVersProfil,
    EcoleVersForm,
    AjoutFavorisEnseignant,
    RetraitFavorisEnseignant,
    AjoutPosulationEnseignant,
    ModifPosulationEnseignant,
    RetraitPosulationEnseignant,
    EnseignantVersDashboard,
    EnseignantVersForm,
    EnseignantVersProfil,
    SupprimerEcole,
    SupprimerEnseignant,
}
