package org.amire.progav_finalproj.utils;

public enum ActionTypes {
    ToLogin,
    ToRegister,
    Login,
    StartRegister,
    EndRegister,
    Logout,
    AjoutFavorisEcole,
    RetraitFavorisEcole,
    AjoutPostulationEcole,
    AccepterPostulationEcole,
    RefuserPostulationEcole,
    ModifPostulationEcole,
    RetraitPostulationEcole,
    EcoleVersDashboard,
    EcoleVersProfil,
    EcoleVersForm,
    EcoleVersMatch,
    EnseignantVersMatch,
    AjoutFavorisEnseignant,
    RetraitFavorisEnseignant,
    AjoutPostulationEnseignant,
    AccepterPostulationEnseignant,
    RefuserPostulationEnseignant,
    ModifPostulationEnseignant,
    RetraitPostulationEnseignant,
    EnseignantVersDashboard,
    EnseignantVersForm,
    EnseignantVersProfil,
    SupprimerEcole,
    SupprimerEnseignant,
    ModifierProfil,
    Recherche,
    ModifierMdp,
}
