package org.amire.progav_finalproj.utils;

public enum ActionTypes {
    Entry,
    Details,
    Edit,
    Supprimer,
    Login,
    Logout,
    Retour,
    AjoutFavorisEcole,
    RetraitFavorisEcole,
    AjoutPosulationEcole,
    RetraitPosulationEcole,
    EcoleVersDashboard,
    EcoleVersProfil,
    AjoutFavorisEnseignant,
    RetraitFavorisEnseignant,
    AjoutPosulationEnseignant,
    RetraitPosulationEnseignant,
    EnseignantVersDashboard,
    EnseignantVersProfil,
    SupprimerEcole,
    SupprimerEnseignant,
}
